// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortFolioFInal.Data;

#nullable disable

namespace PortFolioFInal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240303191917_seedTables")]
    partial class seedTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortFolioFInal.Models.Login", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Email = "",
                            details = "This is my details1",
                            title = "Title1"
                        });
                });

            modelBuilder.Entity("PortFolioFInal.Models.Project", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("projectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projectLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            id = 1,
                            projectDescription = "This is my project1",
                            projectLink = "https://github.com/abc",
                            projectName = "Project1"
                        },
                        new
                        {
                            id = 2,
                            projectDescription = "This is Project2",
                            projectLink = "https://github.com/abcd",
                            projectName = "Project2"
                        },
                        new
                        {
                            id = 3,
                            projectDescription = "This is my Project3",
                            projectLink = "https://github.com/abcde",
                            projectName = "Project3"
                        });
                });

            modelBuilder.Entity("PortFolioFInal.Models.Skill", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("level")
                        .HasColumnType("int");

                    b.Property<string>("skillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            id = 1,
                            level = 5,
                            skillName = "C#"
                        },
                        new
                        {
                            id = 2,
                            level = 4,
                            skillName = "Python"
                        },
                        new
                        {
                            id = 3,
                            level = 3,
                            skillName = "Java"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
